#define WS2812_DI_PIN GP1
#define RGBLIGHT_LED_COUNT 101
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_RGB

#define RGBLIGHT_SLEEP
#define RGBLIGHT_LIMIT_VAL 144
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_HUE 124
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_DEFAULT_SPD 0
#define RGBLIGHT_DEFAULT_ON true
